### ISSUE TITLE
Başarılı

### ISSUE THREAD

**Issue by erailea** [go-who/who#11]
Firmalarını övmek için saçma reklamlara para harcayan o kadar boş firma varken eleman bulmak için böyle bir reklam yapmanız takdire şayan.

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

Guzel yorumunuz icin ayrica cok tesekkurler
