### ISSUE TITLE
Çözülmesi gereken bir kod yada gizem yokmu? Hayal kırıklığı yetenekleri sahada göstersek ya 

### ISSUE THREAD

**Issue by biremk** [go-who/who#13]
Peak yazısında sanki bir şey var gibi ama emin olamadım.Bakalım biraz kurcalayalım.

**Comment by batuhantopalogluu** [comment]
bana da öyle geliyor

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

Bu reponun amaci reklamda kullandigimiz go kodununun derlenebildigini ve sorunsuz calistirilabilecegini gostermektir. Maalesef bu minik repo bircok arkadasimizin bekledigi gibi bir bulmaca icermiyor :)

Peak open source projelerine katkida bulunmak isterseniz [https://github.com/peakgames](https://github.com/peakgames) adresine goz atabilirsiniz.

Gelismeye, gelistirmeye devam...
