### ISSUE TITLE
Burayı bulan az kişiyiz

### ISSUE THREAD

**Issue by ghost** [go-who/who#15]
İyi güzel hoşta bi' bulmaca base64 falan yapaydınız olmazki böyle kuru kuru

**Comment by eSisman3** [comment]
Bence bir şifre var bulacağız sıkıntı yok

**Comment by erenilhan** [comment]
Kafayı yedirdiler sonunda :)

**Comment by ghost** [comment]
Var bişeyler ben eminim bu gece Go dilini bi araştırayım bu işte bi iş var

**Comment by alperen** [comment]
merhaba ben yorum yapmaya geldim, buglar var onları çözelim 👍

**Comment by mstfa45** [comment]
Olayımız nedir tam olarak

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

Bu reponun amaci reklamda kullandigimiz go kodununun derlenebildigini ve sorunsuz calistirilabilecegini gostermektir. Maalesef bu minik repo bircok arkadasimizin bekledigi gibi bir bulmaca icermiyor :)

Peak open source projelerine katkida bulunmak isterseniz [https://github.com/peakgames](https://github.com/peakgames) adresine goz atabilirsiniz.

Gelismeye, gelistirmeye devam...
