### ISSUE TITLE
Bir şifre olmalı

### ISSUE THREAD

**Issue by Efril1** [go-who/who#17]
Puzzle falan

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

Bu reponun amaci reklamda kullandigimiz go kodununun derlenebildigini ve sorunsuz calistirilabilecegini gostermektir. Maalesef bu minik repo bircok arkadasimizin bekledigi gibi bir bulmaca/sifre  icermiyor :)

Peak open source projelerine katkida bulunmak isterseniz [https://github.com/peakgames](https://github.com/peakgames) adresine goz atabilirsiniz.

Gelismeye, gelistirmeye devam...

**Comment by Efril1** [comment]
İlginiz için sağ olun fakat şu an niteliksiz bir üniversite hazırlık
öğrencisiyim. ODTÜ Elektrik elektronik mühendisliği istiyorum sizin gibi
ana uğraşı mobil oyunlar  olan bir firmaya pek yardımcı olamam.
Gerçi mobil oyun yapmışlığım vardır tabi amatör düzeyde...
Reklamınızı tebrik ediyorum.Gelişmenizi diliyorum.

21 Şub 2019 Per ÖÖ 9:52 tarihinde İlkin Balkanay <notifications@github.com>
şunu yazdı:
