### ISSUE TITLE
Bulmamızı istedikleri yer burası mıydı?

### ISSUE THREAD

**Issue by rabe61** [go-who/who#21]
Farklı bir şey vardır elbet.

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

Bu reponun amaci reklamda kullandigimiz go kodununun derlenebildigini ve sorunsuz calistirilabilecegini gostermektir. Maalesef bu minik repo bircok arkadasimizin bekledigi gibi bir bulmaca/sifre icermiyor 😄

**Comment by rabe61** [comment]
İşsizlik durumu ortada. İnsanların bir iş gördüğü zaman ciğer görmüş kedi
gibi atlaması normal. Yaşım küçük, sadece kendi başıma yazılım öğrenmeye
çalışıyorum tabi bayağı zorlanıyorhm. Heyecan olsun diye merak edip
araştırayım demiştim bi baktım hayatınızı öğrenmişim. Önceki
çalışmalarınızada bir göz gezdirdim çok hoşuma gitti. Sizin gibi değerli
bir insanın hayatını öğrenmiş oldum en azından :)

21 Şub 2019 Per 09:58 tarihinde İlkin Balkanay <notifications@github.com>
şunu yazdı:
