### ISSUE TITLE
Tanışalım mı?

### ISSUE THREAD

**Issue by Nari16** [go-who/who#25]
Merhaba,

Cevap geleceğini sanmıyorum ama, bir deneyelim bakalım.

İyi günler.

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.
