### ISSUE TITLE
Eee Başka ?

### ISSUE THREAD

**Issue by bzkrt45** [go-who/who#26]

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.
Hepsi bu kadar 😄 

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

Bu reponun amaci reklamda kullandigimiz go kodununun derlenebildigini ve sorunsuz calistirilabilecegini gostermektir. Maalesef bu minik repo bircok arkadasimizin bekledigi gibi bir bulmaca/sifre icermiyor :)
