### ISSUE TITLE
Sanırım üniversite mezunu donanımlı arkadaşları falan arıyorlar.

### ISSUE THREAD

**Issue by msifo** [go-who/who#27]

**Comment by msifo** [comment]
Yani ben değilim. Ödevimden alıkoydunuz, saçma sapan takılıyorum buralarda.

**Comment by parsX** [comment]
bizi kimler alsın kardeş

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden size uygun pozisyona basvurunuzu yapmak.
