### ISSUE TITLE
farklı bir şey olmalı

### ISSUE THREAD

**Issue by finirisma** [go-who/who#28]
en azından burayı farkedenler için

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.
