### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [go-who/who#3]

**Comment by parsX** [comment]
cidden kendimden şüphe ettim gözüm daha fazlasını arıyor

**Comment by ermanmanyasli** [comment]
yok bişi bir puzzle bekledim bende.  Cicada 3301 gibi bişi bekledim

**Comment by parsX** [comment]
bende öyle birşey beklemiştim ama olsun daha önce böyle birşey türkiyede
görmemiştik iyi oldu

Erman Manyaslı <notifications@github.com>, 18 Şub 2019 Pzt, 22:13 tarihinde
şunu yazdı:

**Comment by eSisman3** [comment]
Yok Mu Bize Özel Güzellikler Buraya Kadar Geldik

**Comment by parsX** [comment]
olmaz mı


eSisman3 <notifications@github.com>, 18 Şub 2019 Pzt, 22:16 tarihinde şunu
yazdı:

**Comment by parsX** [comment]
hocam vallahi elimizde patladı bi heyecanla geldik

Kaan Subaz <flammingfury@gmail.com>, 18 Şub 2019 Pzt, 22:17 tarihinde şunu
yazdı:

**Comment by eSisman3** [comment]
Aynen ya aslında çok sağlam viral reklam olurmuş

**Comment by ofdemir** [comment]
Reklam orjinal değil ki altından ekstra orjinal bişey çıksın. Audi reklamını uyarlamışlar, müzik bile aynı ama başarılı mı başarılı.

**Comment by ertence** [comment]
Tek olmadığımı görmek mutlu etti açıkçası .d

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

Bu reponun amaci reklamda kullandigimiz go kodununun derlenebildigini ve sorunsuz calistirilabilecegini gostermektir. Maalesef bu minik repo bircok arkadasimizin bekledigi gibi bir bulmaca icermiyor :)

Peak open source projelerine katkida bulunmak isterseniz [https://github.com/peakgames](https://github.com/peakgames) adresine goz atabilirsiniz.

Gelismeye, gelistirmeye devam...
