### ISSUE TITLE
başvuru

### ISSUE THREAD

**Issue by alpertunga333** [go-who/who#30]
kodu çözenlerden başvuru kabul edilecek

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

Bu reponun amaci reklamda kullandigimiz go kodununun derlenebildigini ve sorunsuz calistirilabilecegini gostermektir. Maalesef bu minik repo bircok arkadasimizin bekledigi gibi bir bulmaca/sifre icermiyor :)

Yazilim bulmacalari cozmeyi seviyorsaniz https://adventofcode.com/ burada cok iyi bulmacalar var.
