### ISSUE TITLE
Her zaman:S

### ISSUE THREAD

**Issue by salihakar1** [go-who/who#32]

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler 😄 

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.
