### ISSUE TITLE
Bende Buradayım,

### ISSUE THREAD

**Issue by lodos2005** [go-who/who#33]
öylesine bir mesajım bulunsun.

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler 😄 

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.
