### ISSUE TITLE
WeAre() Here

### ISSUE THREAD

**Issue by BerkcanCengiz** [go-who/who#34]
Buradayız.

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler 😄 

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.
