### ISSUE TITLE
About your open source licence

### ISSUE THREAD

**Issue by tolgacesur** [go-who/who#36]
We didn't see anything about the license in this repository. What do you think of the video below?

https://www.youtube.com/watch?v=ElbnpKX0qSY

**Comment by trK54Ylmz** [comment]
Finally!

**Comment by semihbayindir** [comment]
I hope they have an explanation.

**Comment by trK54Ylmz** [comment]
Audi Safety Code awareness video + CyberPunk 2077 E3 trailer intro

**Comment by tolgacesur** [comment]
@trK54Ylmz Hi,

I don't know but these kinds of situations can be common in the **advertising industry**. As @semihbayindir  says, maybe they have an explanation.

**Comment by tolgacesur** [comment]
Look here. Closed for :

https://twitter.com/PeakCom/status/1097794469154430977?s=19
