### ISSUE TITLE
Biz burdayiz

### ISSUE THREAD

**Issue by CevatAYDN** [go-who/who#38]
Ogrenilecek cok sey var

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

**Comment by CevatAYDN** [comment]
Asil ben ilginize tesekkur ederim. Basvurumu yaptim sonuclanmasini
beklemekteyim

21 Şub 2019 Per 10:16 tarihinde İlkin Balkanay <notifications@github.com>
şunu yazdı:
