### ISSUE TITLE
Sıfırdan baslamak

### ISSUE THREAD

**Issue by Berazed** [go-who/who#40]
Bu memleket için birşeyler yapmak için . Sizler gibi sıfırdan başlamak isterim.

**Comment by mstfa45** [comment]
Eksiden de başlayabilirim

**Comment by ilkinulas** [comment]
Ilginiz  ve guzel yorumunuz icin cok tesekkurler.
Eksiden baslamaya gerek yok 😆 

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.
