### ISSUE TITLE
Güzel reklam tebrikler. 

### ISSUE THREAD

**Issue by ondergenc** [go-who/who#41]

**Comment by mstfa45** [comment]
Biri açıklasın

**Comment by ilkinulas** [comment]
Ilginiz  ve guzel yorumunuz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.
