### ISSUE TITLE
Hello world! 

### ISSUE THREAD

**Issue by xarsess** [go-who/who#42]
Eğlenceliydi tebrik ederim..

**Comment by mstfa45** [comment]
Eğlenceyi çözemedik tam

**Comment by ilkinulas** [comment]
Ilginiz icin ve guzel yorumunuz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

Bu reponun amaci reklamda kullandigimiz go kodununun derlenebildigini ve sorunsuz calistirilabilecegini gostermektir. Maalesef bu minik repo bircok arkadasimizin bekledigi gibi bir bulmaca/sifre icermiyor :)
