### ISSUE TITLE
Reklam efsane

### ISSUE THREAD

**Issue by Oguzxxx** [go-who/who#47]
Çok iyi düşünülmüş bir reklam :)

**Comment by ilkinulas** [comment]
Ilginiz ve guzel yorumunuz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.
