### ISSUE TITLE
İyi iş çıkardınız..

### ISSUE THREAD

**Issue by webwarrior06** [go-who/who#50]
Reklam güzeldi. İnsanlar kumandayı falan attı korkudan. Sakin olun Türkiye daha hazır değil böyle şeylere 😁

**Comment by ilkinulas** [comment]
Ilginiz ve guzel yorumunuz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.
