### ISSUE TITLE
Oldukça heyecan verici.. 

### ISSUE THREAD

**Issue by msbsvg** [go-who/who#52]
Bir reklamdan çok daha fazlasıydı.. Biraz reklam, biraz meydan okuma, biraz sosyal deney.. Belki biraz da bulmaca da vardır diye geldik buralara..

Başarılarınızın devamını dilerim!

**Comment by ilkinulas** [comment]
Ilginiz ve guzel yorumunuz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

Bu reponun amaci reklamda kullandigimiz go kodununun derlenebildigini ve sorunsuz calistirilabilecegini gostermektir. Maalesef bu minik repo bircok arkadasimizin bekledigi gibi bir bulmaca/sifre icermiyor :)
