### ISSUE TITLE
Hi There 

### ISSUE THREAD

**Issue by yyyalmanci** [go-who/who#53]
Burdayız biz de

**Comment by ilkinulas** [comment]
Selam 🖖 

Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.
