### ISSUE TITLE
Sıra sende

### ISSUE THREAD

**Issue by kerimacuner** [go-who/who#56]
ben seni buldum sıra sende.

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.
