### ISSUE TITLE
11. Satır

### ISSUE THREAD

**Issue by msbsvg** [go-who/who#58]
https://github.com/go-who/who/blob/b95eeabac7891ed7598c8aaaa7db393ace16503a/who.go#L11

Nedense bir mesaj, bir bulmaca, bir şifre var mıdır acaba diye özellikle de 11. satıra uzun uzun baktım.. Barış Özcan'ın bu reklam filmi ile tesadüfi zamanlamalı son youtube videosu da tabi etkili olmadı değil :)

**Comment by ilkinulas** [comment]
Ilginiz  icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

Bu reponun amaci reklamda kullandigimiz go kodununun derlenebildigini ve sorunsuz calistirilabilecegini gostermektir. Maalesef bu minik repo bircok arkadasimizin bekledigi gibi bir bulmaca/sifre icermiyor :)

Yazilim bulmacalari cozmeyi seviyorsaniz https://adventofcode.com/ burada cok iyi bulmacalar var.
