### ISSUE TITLE
Tebrik ederim. Blöf sanıp kanal değiştirdim :)

### ISSUE THREAD

**Issue by SerdarDemirbas** [go-who/who#61]
Değilmiş :)

**Comment by ilkinulas** [comment]
Evet blof yapmiyorduk 😆  

Ilginiz ve guzel yorumunuz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.
