### ISSUE TITLE
reklam_efsaneidi

### ISSUE THREAD

**Issue by kubilayoo7** [go-who/who#64]
hayatımda gördüğüm en iyi reklamdı. çok büyük keyif aldım biz birilerini arıyoruz :D

**Comment by ilkinulas** [comment]
Ilginiz ve guzel yorumunuz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

**Comment by kubilayoo7** [comment]
İlginize çok teşekkür ederim şansımı deniyeceğim

21 Şub 2019 Per 10:33 tarihinde İlkin Balkanay <notifications@github.com>
şunu yazdı:
