### ISSUE TITLE
Selam peak

### ISSUE THREAD

**Issue by sherlocksback** [go-who/who#67]
Çok güzel reklam yapmışsınız şifreyi bulduğuma sevindim

**Comment by ilkinulas** [comment]
Ilginiz ve guzel yorumunuz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

Bu reponun amaci reklamda kullandigimiz go kodununun derlenebildigini ve sorunsuz calistirilabilecegini gostermektir. Maalesef bu minik repo bircok arkadasimizin bekledigi gibi bir bulmaca/sifre icermiyor :)
