### ISSUE TITLE
Hayal kırıklığı...

### ISSUE THREAD

**Issue by rownL** [go-who/who#69]
Biraz heyecanlandırdı ilk başta fakat reklamın kendisi orijinal değilmiş yani yaratıcılık başka bir yerden alınmış "sıfır emek!" hemen hevesimi kursağımda bıraktı; link: https://youtu.be/ElbnpKX0qSY

Hayal gücü, merak vb. denilip basbaya tecrübe aranıyor zaten, biraz merak edenler kurcalayıp hüsrana uğrayabilirler. 
Hayatta bol şans dilerim buraya kadar gelen arkadaşlara.

**Comment by ilkinulas** [comment]
Konu ile ilgili aciklamamiz : https://twitter.com/PeakCom/status/1097794469154430977

ilginiz icin tesekkurler
