### ISSUE TITLE
Haydi Tanışalım peak

### ISSUE THREAD

**Issue by parsX** [go-who/who#7]
sanrımşimdi tanışma zamanı

**Comment by tkopter** [comment]
öyle mi?

**Comment by parsX** [comment]
öyle


tkopter <notifications@github.com>, 18 Şub 2019 Pzt, 22:17 tarihinde şunu
yazdı:

**Comment by tkopter** [comment]
hadi.

**Comment by parsX** [comment]
ben sıradan bi insanım ya sen ?



tkopter <notifications@github.com>, 18 Şub 2019 Pzt, 22:19 tarihinde şunu
yazdı:

**Comment by ilkinulas** [comment]
Ilginiz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz tanismak  icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.

Gorusuruz
