### ISSUE TITLE
Bu kadar mıydı

### ISSUE THREAD

**Issue by berkekbgz** [go-who/who#70]

**Comment by ilkinulas** [comment]
Ilginiz ve guzel yorumunuz icin cok tesekkurler.

Reklamdaki kodu takip ederek buraya kadar gelmeniz cok guzel. Bundan sonraki adim hala yapmadiysaniz takima katilmak ve tanismak icin [https://www.peak.com/jobs](https://www.peak.com/jobs)  adresinden basvurunuzu yapmak.
